# Site settings
title: Accessbolaget
email: info@accessbolaget.se
description: > # this means to ignore newlines until "baseurl:"
  Accessbolaget är namnet på vårt bolag – och vi kan på stadsnätens infrastruktur leverera moderna och flexibla Carrier Ethernet-tjänster med bandbredder från 10 Mbit/s till 10 Gbit/s till företagsmarknaden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
stylus:
  compress: true
  path: /css/
